spring:
  application:
    name: enterprise-ai-platform
  datasource:
    url: jdbc:mysql://localhost:3306/aiplatform?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: localhost
    port: 6379
    timeout: 10000
    database: 0

server:
  port: 8080
  servlet:
    context-path: /api/v1

# JWT配置
jwt:
  secret: 5ecr3tK3y4EnterpriseAIPlatform2025SecureJWTToken
  expiration: 86400000 # 24小时
  header: Authorization
  prefix: Bearer 

# 日志配置
logging:
  level:
    root: INFO
    com.enterprise.aiplatform: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

# 应用自定义配置
app:
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  upload:
    max-file-size: 10MB
    allowed-types: application/pdf,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document
    storage-path: /uploads
  cache:
    default-ttl: 86400 # 24小时